<a href="https://colab.research.google.com/github/StefanoBergia/Tensorflow/blob/main/SimpleRNN_Shapes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
print(tf.__version__)

2.8.0


In [3]:
from tensorflow.keras.layers import Input,Dense,SimpleRNN
from tensorflow.keras.models import Model 
from tensorflow.keras.optimizers import SGD, Adam

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
# N = number of samples
# T = sequence lenght
# D = number of features
# M = number of hidden units
# K = number of output units

In [5]:
N = 1
T = 10
D = 3
K =2
X = np.random.randn(N,T,D)

In [6]:

M=5

i=Input(shape=(T,D))
x=SimpleRNN(M)(i)   #activation None, (è un regressore)
x=Dense(K)(x)

model=Model(i,x)

In [7]:
Yhat=model.predict(X)
print(Yhat)

[[-0.1594982 -0.9167178]]


In [8]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 10, 3)]           0         
                                                                 
 simple_rnn (SimpleRNN)      (None, 5)                 45        
                                                                 
 dense (Dense)               (None, 2)                 12        
                                                                 
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [9]:
model.layers[1].get_weights()

[array([[-0.5392734 ,  0.6758488 , -0.2886821 , -0.84184265,  0.6212923 ],
        [-0.40376487,  0.24846894, -0.20741683, -0.21547127, -0.46824935],
        [-0.02596712,  0.57341903,  0.20895845, -0.3446977 , -0.654166  ]],
       dtype=float32),
 array([[-0.89183664,  0.28456187,  0.25484064,  0.13903117,  0.19844082],
        [-0.17907117, -0.18981312, -0.50918794,  0.72375345, -0.38576275],
        [-0.17667589, -0.9268593 ,  0.28874776,  0.00284612,  0.16227758],
        [ 0.03082106,  0.05343003,  0.62595093,  0.04845782, -0.7759075 ],
        [-0.3746957 , -0.14516354, -0.44787702, -0.6741625 , -0.42830113]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [10]:
a,b,c=model.layers[1].get_weights()
print(a.shape,b.shape,c.shape)

(3, 5) (5, 5) (5,)


In [11]:
Wx,Wh,bh=model.layers[1].get_weights()
Wo,bo=model.layers[2].get_weights()

In [12]:
h_last=np.zeros(M)
x=X[0]
Yhats=[]

for t in range(T):
  h=np.tanh(x[t].dot(Wx)+h_last.dot(Wh)+bh)
  y=h.dot(Wo)+bo
  Yhats.append(y)

  h_last=h

print(Yhats[-1])

[-0.15949825 -0.91671775]
